In [1]:
import pandas as pd
from pprint import pprint

# Creating the dataframe and viewing the data

In [2]:
# Creating a dataframe from the csv data
data_id = "T001"
raw_data_csv_path = "/Users/hlinero/Desktop/iTEM Material/raw dataset/T001/"
df = pd.read_csv(raw_data_csv_path+"T001_ITF_GOODS_TRANSPORT_25102019112251109.csv")
df.head(50)

,COUNTRY,Country,VARIABLE,Variable,YEAR,Year,Unit Code,Unit,PowerCode Code,PowerCode,Reference Period Code,Reference Period,Value,Flag Codes,Flags
0,CAN,Canada,T-SEA-CAB,Coastal shipping (national transport),1995,1995,TONNEKM,Tonnes-kilometres,6,Millions,NaN,NaN,10369.0,NaN,NaN
1,CAN,Canada,T-SEA-CAB,Coastal shipping (national transport),1996,1996,TONNEKM,Tonnes-kilometres,6,Millions,NaN,NaN,10166.0,NaN,NaN
2,CAN,Canada,T-SEA-CAB,Coastal shipping (national transport),1997,1997,TONNEKM,Tonnes-kilometres,6,Millions,NaN,NaN,10735.0,NaN,NaN
3,CAN,Canada,T-SEA-CAB,Coastal shipping (national transport),1998,1998,TONNEKM,Tonnes-kilometres,6,Millions,NaN,NaN,13420.0,NaN,NaN
4,CAN,Canada,T-SEA-CAB,Coastal shipping (national transport),1999,1999,TONNEKM,Tonnes-kilometres,6,Millions,NaN,NaN,14144.0,NaN,NaN
5,CAN,Canada,T-SEA-CAB,Coastal shipping (national transport),2000,2000,TONNEKM,Tonnes-kilometres,6,Millions,NaN,NaN,13891.0,NaN,NaN
6,CAN,Canada,T-SEA-CAB,Coastal shipping (national transport),2001,2001,TONNEKM,Tonnes-kilometres,6,Millions,NaN,NaN,15055.0,NaN,NaN
7,CAN,Canada,T-SEA-CAB,Coastal shipping (national transport),2002,2002,TONNEKM,Tonnes-kilometres,6,Millions,NaN,NaN,21451.0,NaN,NaN
8,CAN,Canada,T-SEA-CAB,Coastal shipping (national transport),2003,2003,TONNEKM,Tonnes-kilometres,6,Millions,NaN,NaN,25517.0,NaN,NaN
9,CAN,Canada,T-SEA-CAB,Coastal shipping (national transport),2004,2004,TONNEKM,Tonnes-kilometres,6,Millions,NaN,NaN,25329.0,NaN,NaN
10,CAN,Canada,T-SEA-CAB,Coastal shipping (national transport),2005,2005,TONNEKM,Tonnes-kilometres,6,Millions,NaN,NaN,24450.0,NaN,NaN
11,CAN,Canada,T-SEA-CAB,Coastal shipping (national transport),2006,2006,TONNEKM,Tonnes-kilometres,6,Millions,NaN,NaN,24881.0,NaN,NaN
12,CAN,Canada,T-SEA-CAB,Coastal shipping (national transport),2007,2007,TONNEKM,Tonnes-kilometres,6,Millions,NaN,NaN,29388.0,NaN,NaN
13,CAN,Canada,T-SEA-CAB,Coastal shipping (national transport),2008,2008,TONNEKM,Tonnes-kilometres,6,Millions,NaN,NaN,27852.0,NaN,NaN
14,CAN,Canada,T-SEA-CAB,Coastal shipping (national transport),2009,2009,TONNEKM,Tonnes-kilometres,6,Millions,NaN,NaN,26678.0,NaN,NaN
15,CAN,Canada,T-SEA-CAB,Coastal shipping (national transport),2010,2010,TONNEKM,Tonnes-kilometres,6,Millions,NaN,NaN,29547.0,NaN,NaN
16,CAN,Canada,T-SEA-CAB,Coastal shipping (national transport),2011,2011,TONNEKM,Tonnes-kilometres,6,Millions,NaN,NaN,31735.0,NaN,NaN
17,SWE,Sweden,T-SEA-CAB,Coastal shipping (national transport),1970,1970,TONNEKM,Tonnes-kilometres,6,Millions,NaN,NaN,5200.0,NaN,NaN
18,SWE,Sweden,T-SEA-CAB,Coastal shipping (national transport),1971,1971,TONNEKM,Tonnes-kilometres,6,Millions,NaN,NaN,5500.0,NaN,NaN
19,SWE,Sweden,T-SEA-CAB,Coastal shipping (national transport),1972,1972,TONNEKM,Tonnes-kilometres,6,Millions,NaN,NaN,5900.0,NaN,NaN
20,SWE,Sweden,T-SEA-CAB,Coastal shipping (national transport),1973,1973,TONNEKM,Tonnes-kilometres,6,Millions,NaN,NaN,6300.0,NaN,NaN
21,SWE,Sweden,T-SEA-CAB,Coastal shipping (national transport),1974,1974,TONNEKM,Tonnes-kilometres,6,Millions,NaN,NaN,7200.0,NaN,NaN
22,SWE,Sweden,T-SEA-CAB,Coastal shipping (national transport),1975,1975,TONNEKM,Tonnes-kilometres,6,Millions,NaN,NaN,8200.0,NaN,NaN
23,SWE,Sweden,T-SEA-CAB,Coastal shipping (national transport),1976,1976,TONNEKM,Tonnes-kilometres,6,Millions,NaN,NaN,9293.0,NaN,NaN
24,SWE,Sweden,T-SEA-CAB,Coastal shipping (national transport),1977,1977,TONNEKM,Tonnes-kilometres,6,Millions,NaN,NaN,9340.0,NaN,NaN
25,SWE,Sweden,T-SEA-CAB,Coastal shipping (national transport),1978,1978,TONNEKM,Tonnes-kilometres,6,Millions,NaN,NaN,8650.0,NaN,NaN
26,SWE,Sweden,T-SEA-CAB,Coastal shipping (national transport),1979,1979,TONNEKM,Tonnes-kilometres,6,Millions,NaN,NaN,10163.0,NaN,NaN
27,SWE,Sweden,T-SEA-CAB,Coastal shipping (national transport),1980,1980,TONNEKM,Tonnes-kilometres,6,Millions,NaN,NaN,10256.0,NaN,NaN
28,SWE,Sweden,T-SEA-CAB,Coastal shipping (national transport),1981,1981,TONNEKM,Tonnes-kilometres,6,Millions,NaN,NaN,9364.0,NaN,NaN
29,SWE,Sweden,T-SEA-CAB,Coastal shipping (national transport),1982,1982,TONNEKM,Tonnes-kilometres,6,Millions,NaN,NaN,9381.0,NaN,NaN
30,SWE,Sweden,T-SEA-CAB,Coastal shipping (national transport),1983,1983,TONNEKM,Tonnes-kilometres,6,Millions,NaN,NaN,9209.0,NaN,NaN
31,SWE,Sweden,T-SEA-CAB,Coastal shipping (national transport),1984,1984,TONNEKM,Tonnes-kilometres,6,Millions,NaN,NaN,9144.0,NaN,NaN
32,SWE,Sweden,T-SEA-CAB,Coastal shipping (national transport),1985,1985,TONNEKM,Tonnes-kilometres,6,Millions,NaN,NaN,9183.0,NaN,NaN
33,SWE,Sweden,T-SEA-CAB,Coastal shipping (national transport),1986,1986,TONNEKM,Tonnes-kilometres,6,Millions,NaN,NaN,9447.0,NaN,NaN
34,SWE,Sweden,T-SEA-CAB,Coastal shipping (national transport),1987,1987,TONNEKM,Tonnes-kilometres,6,Millions,NaN,NaN,8665.0,NaN,NaN
35,SWE,Sweden,T-SEA-CAB,Coastal shipping (national transport),1988,1988,TONNEKM,Tonnes-kilometres,6,Millions,NaN,NaN,7859.0,NaN,NaN
36,SWE,Sweden,T-SEA-CAB,Coastal shipping (national transport),1989,1989,TONNEKM,Tonnes-kilometres,6,Millions,NaN,NaN,7853.0,NaN,NaN
37,SWE,Sweden,T-SEA-CAB,Coastal shipping (national transport),1990,1990,TONNEKM,Tonnes-kilometres,6,Millions,NaN,NaN,7900.0,NaN,NaN
38,SWE,Sweden,T-SEA-CAB,Coastal shipping (national transport),1991,1991,TONNEKM,Tonnes-kilometres,6,Millions,NaN,NaN,7538.0,NaN,NaN
39,SWE,Sweden,T-SEA-CAB,Coastal shipping (national transport),1992,1992,TONNEKM,Tonnes-kilometres,6,Millions,NaN,NaN,7091.0,NaN,NaN
40,SWE,Sweden,T-SEA-CAB,Coastal shipping (national transport),1993,1993,TONNEKM,Tonnes-kilometres,6,Millions,NaN,NaN,7349.0,NaN,NaN
41,SWE,Sweden,T-SEA-CAB,Coastal shipping (national transport),1994,1994,TONNEKM,Tonnes-kilometres,6,Millions,NaN,NaN,7641.0,NaN,NaN
42,SWE,Sweden,T-SEA-CAB,Coastal shipping (national transport),1995,1995,TONNEKM,Tonnes-kilometres,6,Millions,NaN,NaN,8274.0,NaN,NaN
43,SWE,Sweden,T-SEA-CAB,Coastal shipping (national transport),1996,1996,TONNEKM,Tonnes-kilometres,6,Millions,NaN,NaN,8634.0,NaN,NaN
44,SWE,Sweden,T-SEA-CAB,Coastal shipping (national transport),1997,1997,TONNEKM,Tonnes-kilometres,6,Millions,NaN,NaN,8387.0,NaN,NaN
45,SWE,Sweden,T-SEA-CAB,Coastal shipping (national transport),1998,1998,TONNEKM,Tonnes-kilometres,6,Millions,NaN,NaN,8334.0,NaN,NaN
46,SWE,Sweden,T-SEA-CAB,Coastal shipping (national transport),1999,1999,TONNEKM,Tonnes-kilometres,6,Millions,NaN,NaN,7700.0,NaN,NaN
47,SWE,Sweden,T-SEA-CAB,Coastal shipping (national transport),2000,2000,TONNEKM,Tonnes-kilometres,6,Millions,NaN,NaN,8118.0,NaN,NaN
48,SWE,Sweden,T-SEA-CAB,Coastal shipping (national transport),2001,2001,TONNEKM,Tonnes-kilometres,6,Millions,NaN,NaN,7579.0,NaN,NaN
49,SWE,Sweden,T-SEA-CAB,Coastal shipping (national transport),2002,2002,TONNEKM,Tonnes-kilometres,6,Millions,NaN,NaN,7183.0,NaN,NaN

# General Info About the Data

In [3]:
# Getting general info about the data
rows, cols = df.shape
print(">> Number of Columns: {}".format(cols))
print(">> Number of Rows: {}".format(rows))

# Grouping the data by Countries
group_by_country = df.groupby(df.Country)
list_of_countries = list(group_by_country.groups.keys())
print(">> Number of countries: {}".format(len(list_of_countries)))

>> Number of Columns: 15
>> Number of Rows: 1579
>> Number of countries: 40

# Removing all unnecessary columns

### Rule: To comply with the latest template, we will drop all the unnecessary columns and rename others.

In [4]:
# Droping the repeated columns
columns_to_delete = ["COUNTRY", "YEAR", "VARIABLE","Reference Period Code","Unit Code","Reference Period", "Flag Codes", "Flags", "PowerCode Code"]
df.drop(columns=columns_to_delete, inplace = True)
df.rename(columns={"Country":"Region"}, inplace = True)
df

,Region,Variable,Year,Unit,PowerCode,Value
0,Canada,Coastal shipping (national transport),1995,Tonnes-kilometres,Millions,10369.0
1,Canada,Coastal shipping (national transport),1996,Tonnes-kilometres,Millions,10166.0
2,Canada,Coastal shipping (national transport),1997,Tonnes-kilometres,Millions,10735.0
3,Canada,Coastal shipping (national transport),1998,Tonnes-kilometres,Millions,13420.0
4,Canada,Coastal shipping (national transport),1999,Tonnes-kilometres,Millions,14144.0
...,...,...,...,...,...,...
1574,Czech Republic,Coastal shipping (national transport),2014,Tonnes-kilometres,Millions,NaN
1575,Czech Republic,Coastal shipping (national transport),2015,Tonnes-kilometres,Millions,NaN
1576,Czech Republic,Coastal shipping (national transport),2016,Tonnes-kilometres,Millions,NaN
1577,Czech Republic,Coastal shipping (national transport),2017,Tonnes-kilometres,Millions,NaN
1578,Czech Republic,Coastal shipping (national transport),2018,Tonnes-kilometres,Millions,NaN

## Getting a generic idea of what countries are missing values and dropping NaN values
    Rule: Erase all value with NaN

In [5]:
list_of_countries_with_missing_values = list(set(df[df['Value'].isnull()]["Region"]))
print(">> Number of countries missing values: {}".format(len(list_of_countries_with_missing_values)))
print(">> Countries missing values:")
pprint(list_of_countries_with_missing_values)
print(">> Number of rows to erase: {}".format(len(df[df['Value'].isnull()])))

>> Number of countries missing values: 16
>> Countries missing values:
['North Macedonia',
 'Lithuania',
 'Hungary',
 'Czech Republic',
 'Serbia, Republic of',
 'Greece',
 'Moldova',
 'Liechtenstein',
 'Belarus',
 'Luxembourg',
 'Montenegro, Republic of',
 'Slovak Republic',
 'Switzerland',
 'Armenia',
 'Austria',
 'Slovenia']
>> Number of rows to erase: 750

In [6]:
# Dropping the values
df.dropna(inplace = True)

# Adding the "Source Column"
    Rule: Add the same source to all rows since all data comes from same source

In [7]:
# Creating the values for the source column
source_column = ["International Transport Forum"] * len(df)

# Adding the column to the dataframe
df.insert(0,"Source", source_column, True)
df

,Source,Region,Variable,Year,Unit,PowerCode,Value
0,International Transport Forum,Canada,Coastal shipping (national transport),1995,Tonnes-kilometres,Millions,10369.0
1,International Transport Forum,Canada,Coastal shipping (national transport),1996,Tonnes-kilometres,Millions,10166.0
2,International Transport Forum,Canada,Coastal shipping (national transport),1997,Tonnes-kilometres,Millions,10735.0
3,International Transport Forum,Canada,Coastal shipping (national transport),1998,Tonnes-kilometres,Millions,13420.0
4,International Transport Forum,Canada,Coastal shipping (national transport),1999,Tonnes-kilometres,Millions,14144.0
...,...,...,...,...,...,...,...
1428,International Transport Forum,Turkey,Coastal shipping (national transport),2014,Tonnes-kilometres,Millions,18553.0
1429,International Transport Forum,Turkey,Coastal shipping (national transport),2015,Tonnes-kilometres,Millions,19189.0
1430,International Transport Forum,Turkey,Coastal shipping (national transport),2016,Tonnes-kilometres,Millions,19492.0
1431,International Transport Forum,Turkey,Coastal shipping (national transport),2017,Tonnes-kilometres,Millions,22087.0
1432,International Transport Forum,Turkey,Coastal shipping (national transport),2018,Tonnes-kilometres,Millions,21779.0

# Adding the "Service" column
    Rule: Since all the data is associated to "Freight," the Service is "Freight"

In [8]:
# Creating the values for the source column
service_column = ["Freight"] * len(df)

# Adding the column to the dataframe
df.insert(0,"Service", service_column, True)
df

,Service,Source,Region,Variable,Year,Unit,PowerCode,Value
0,Freight,International Transport Forum,Canada,Coastal shipping (national transport),1995,Tonnes-kilometres,Millions,10369.0
1,Freight,International Transport Forum,Canada,Coastal shipping (national transport),1996,Tonnes-kilometres,Millions,10166.0
2,Freight,International Transport Forum,Canada,Coastal shipping (national transport),1997,Tonnes-kilometres,Millions,10735.0
3,Freight,International Transport Forum,Canada,Coastal shipping (national transport),1998,Tonnes-kilometres,Millions,13420.0
4,Freight,International Transport Forum,Canada,Coastal shipping (national transport),1999,Tonnes-kilometres,Millions,14144.0
...,...,...,...,...,...,...,...,...
1428,Freight,International Transport Forum,Turkey,Coastal shipping (national transport),2014,Tonnes-kilometres,Millions,18553.0
1429,Freight,International Transport Forum,Turkey,Coastal shipping (national transport),2015,Tonnes-kilometres,Millions,19189.0
1430,Freight,International Transport Forum,Turkey,Coastal shipping (national transport),2016,Tonnes-kilometres,Millions,19492.0
1431,Freight,International Transport Forum,Turkey,Coastal shipping (national transport),2017,Tonnes-kilometres,Millions,22087.0
1432,Freight,International Transport Forum,Turkey,Coastal shipping (national transport),2018,Tonnes-kilometres,Millions,21779.0

# Adding the "Technology" and "Fuel" columns
    Rule: The dataset does not provide any data about those two columns, so we added the default value of "All" in both cases.

In [9]:
# Adding the "Technology" and "Fuel" columns
df["Fuel"] = ["All"]*len(df) 
df["Technology"] = ["All"]*len(df)
df

,Service,Source,Region,Variable,Year,Unit,PowerCode,Value,Fuel,Technology
0,Freight,International Transport Forum,Canada,Coastal shipping (national transport),1995,Tonnes-kilometres,Millions,10369.0,All,All
1,Freight,International Transport Forum,Canada,Coastal shipping (national transport),1996,Tonnes-kilometres,Millions,10166.0,All,All
2,Freight,International Transport Forum,Canada,Coastal shipping (national transport),1997,Tonnes-kilometres,Millions,10735.0,All,All
3,Freight,International Transport Forum,Canada,Coastal shipping (national transport),1998,Tonnes-kilometres,Millions,13420.0,All,All
4,Freight,International Transport Forum,Canada,Coastal shipping (national transport),1999,Tonnes-kilometres,Millions,14144.0,All,All
...,...,...,...,...,...,...,...,...,...,...
1428,Freight,International Transport Forum,Turkey,Coastal shipping (national transport),2014,Tonnes-kilometres,Millions,18553.0,All,All
1429,Freight,International Transport Forum,Turkey,Coastal shipping (national transport),2015,Tonnes-kilometres,Millions,19189.0,All,All
1430,Freight,International Transport Forum,Turkey,Coastal shipping (national transport),2016,Tonnes-kilometres,Millions,19492.0,All,All
1431,Freight,International Transport Forum,Turkey,Coastal shipping (national transport),2017,Tonnes-kilometres,Millions,22087.0,All,All
1432,Freight,International Transport Forum,Turkey,Coastal shipping (national transport),2018,Tonnes-kilometres,Millions,21779.0,All,All

# Setting the correct unit name in the "Unit" column
    Rule: Based on the template, the correct unit for "Fraight Activity" is "10^9 tonne-km / yr", so we will assign those units to the data

In [10]:
# Dropping the current "Unit" column
df.drop(columns=["Unit"], inplace = True)

# Adding the new "Unit" column
df["Unit"] = ["10^9 tonne-km / yr"]*len(df) 
df

,Service,Source,Region,Variable,Year,PowerCode,Value,Fuel,Technology,Unit
0,Freight,International Transport Forum,Canada,Coastal shipping (national transport),1995,Millions,10369.0,All,All,10^9 tonne-km / yr
1,Freight,International Transport Forum,Canada,Coastal shipping (national transport),1996,Millions,10166.0,All,All,10^9 tonne-km / yr
2,Freight,International Transport Forum,Canada,Coastal shipping (national transport),1997,Millions,10735.0,All,All,10^9 tonne-km / yr
3,Freight,International Transport Forum,Canada,Coastal shipping (national transport),1998,Millions,13420.0,All,All,10^9 tonne-km / yr
4,Freight,International Transport Forum,Canada,Coastal shipping (national transport),1999,Millions,14144.0,All,All,10^9 tonne-km / yr
...,...,...,...,...,...,...,...,...,...,...
1428,Freight,International Transport Forum,Turkey,Coastal shipping (national transport),2014,Millions,18553.0,All,All,10^9 tonne-km / yr
1429,Freight,International Transport Forum,Turkey,Coastal shipping (national transport),2015,Millions,19189.0,All,All,10^9 tonne-km / yr
1430,Freight,International Transport Forum,Turkey,Coastal shipping (national transport),2016,Millions,19492.0,All,All,10^9 tonne-km / yr
1431,Freight,International Transport Forum,Turkey,Coastal shipping (national transport),2017,Millions,22087.0,All,All,10^9 tonne-km / yr
1432,Freight,International Transport Forum,Turkey,Coastal shipping (national transport),2018,Millions,21779.0,All,All,10^9 tonne-km / yr

# Setting the correct magnitude of the "Value" column
    Rule: The current data is in million. We will convert all values to billions. In which (1M = 0.001B)

In [11]:
# Removing the "PowerCode" column since it is not necessary
df.drop(columns=["PowerCode"], inplace = True)

# Looping though each row and convert each value to billion magnitude
for index, row in df.iterrows():
    current_value = row.Value
    new_value = current_value * float(0.001)
    df.Value[index] = new_value
df

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,Service,Source,Region,Variable,Year,Value,Fuel,Technology,Unit
0,Freight,International Transport Forum,Canada,Coastal shipping (national transport),1995,10.369,All,All,10^9 tonne-km / yr
1,Freight,International Transport Forum,Canada,Coastal shipping (national transport),1996,10.166,All,All,10^9 tonne-km / yr
2,Freight,International Transport Forum,Canada,Coastal shipping (national transport),1997,10.735,All,All,10^9 tonne-km / yr
3,Freight,International Transport Forum,Canada,Coastal shipping (national transport),1998,13.420,All,All,10^9 tonne-km / yr
4,Freight,International Transport Forum,Canada,Coastal shipping (national transport),1999,14.144,All,All,10^9 tonne-km / yr
...,...,...,...,...,...,...,...,...,...
1428,Freight,International Transport Forum,Turkey,Coastal shipping (national transport),2014,18.553,All,All,10^9 tonne-km / yr
1429,Freight,International Transport Forum,Turkey,Coastal shipping (national transport),2015,19.189,All,All,10^9 tonne-km / yr
1430,Freight,International Transport Forum,Turkey,Coastal shipping (national transport),2016,19.492,All,All,10^9 tonne-km / yr
1431,Freight,International Transport Forum,Turkey,Coastal shipping (national transport),2017,22.087,All,All,10^9 tonne-km / yr
1432,Freight,International Transport Forum,Turkey,Coastal shipping (national transport),2018,21.779,All,All,10^9 tonne-km / yr

# Adding the "Mode" column
    Rule: Since all the data is about shipping, all rows have "Shipping" as mode

In [13]:
# Adding the mode columns
df["Mode"] = ["Shipping"]*len(df) 
df

,Service,Source,Region,Variable,Year,Value,Fuel,Technology,Unit,Mode
0,Freight,International Transport Forum,Canada,Coastal shipping (national transport),1995,10.369,All,All,10^9 tonne-km / yr,Shipping
1,Freight,International Transport Forum,Canada,Coastal shipping (national transport),1996,10.166,All,All,10^9 tonne-km / yr,Shipping
2,Freight,International Transport Forum,Canada,Coastal shipping (national transport),1997,10.735,All,All,10^9 tonne-km / yr,Shipping
3,Freight,International Transport Forum,Canada,Coastal shipping (national transport),1998,13.420,All,All,10^9 tonne-km / yr,Shipping
4,Freight,International Transport Forum,Canada,Coastal shipping (national transport),1999,14.144,All,All,10^9 tonne-km / yr,Shipping
...,...,...,...,...,...,...,...,...,...,...
1428,Freight,International Transport Forum,Turkey,Coastal shipping (national transport),2014,18.553,All,All,10^9 tonne-km / yr,Shipping
1429,Freight,International Transport Forum,Turkey,Coastal shipping (national transport),2015,19.189,All,All,10^9 tonne-km / yr,Shipping
1430,Freight,International Transport Forum,Turkey,Coastal shipping (national transport),2016,19.492,All,All,10^9 tonne-km / yr,Shipping
1431,Freight,International Transport Forum,Turkey,Coastal shipping (national transport),2017,22.087,All,All,10^9 tonne-km / yr,Shipping
1432,Freight,International Transport Forum,Turkey,Coastal shipping (national transport),2018,21.779,All,All,10^9 tonne-km / yr,Shipping

# Adding the column "Vehicle Type" 
    Rule: Since all the data in this dataset is associted to coastal shipping, the vehicle type is "Coastal"

In [14]:
# Adding the mode columns
df["Vehicle Type"] = ["Coastal"]*len(df) 
df

,Service,Source,Region,Variable,Year,Value,Fuel,Technology,Unit,Mode,Vehicle Type
0,Freight,International Transport Forum,Canada,Coastal shipping (national transport),1995,10.369,All,All,10^9 tonne-km / yr,Shipping,Coastal
1,Freight,International Transport Forum,Canada,Coastal shipping (national transport),1996,10.166,All,All,10^9 tonne-km / yr,Shipping,Coastal
2,Freight,International Transport Forum,Canada,Coastal shipping (national transport),1997,10.735,All,All,10^9 tonne-km / yr,Shipping,Coastal
3,Freight,International Transport Forum,Canada,Coastal shipping (national transport),1998,13.420,All,All,10^9 tonne-km / yr,Shipping,Coastal
4,Freight,International Transport Forum,Canada,Coastal shipping (national transport),1999,14.144,All,All,10^9 tonne-km / yr,Shipping,Coastal
...,...,...,...,...,...,...,...,...,...,...,...
1428,Freight,International Transport Forum,Turkey,Coastal shipping (national transport),2014,18.553,All,All,10^9 tonne-km / yr,Shipping,Coastal
1429,Freight,International Transport Forum,Turkey,Coastal shipping (national transport),2015,19.189,All,All,10^9 tonne-km / yr,Shipping,Coastal
1430,Freight,International Transport Forum,Turkey,Coastal shipping (national transport),2016,19.492,All,All,10^9 tonne-km / yr,Shipping,Coastal
1431,Freight,International Transport Forum,Turkey,Coastal shipping (national transport),2017,22.087,All,All,10^9 tonne-km / yr,Shipping,Coastal
1432,Freight,International Transport Forum,Turkey,Coastal shipping (national transport),2018,21.779,All,All,10^9 tonne-km / yr,Shipping,Coastal

# Renaming the column "Variable"
    Rule: There is only one activity being perform in this dataset and that is the "Freight Activity". We are setting, for each row, the variable "Freight Activity"

In [15]:
# Dropping the current "Variable" column
df.drop(columns=["Variable"], inplace = True)

# Adding the new "Variable" column with the new data
df["Variable"] = ["Freight Activity"]*len(df)

df

,Service,Source,Region,Year,Value,Fuel,Technology,Unit,Mode,Vehicle Type,Variable
0,Freight,International Transport Forum,Canada,1995,10.369,All,All,10^9 tonne-km / yr,Shipping,Coastal,Freight Activity
1,Freight,International Transport Forum,Canada,1996,10.166,All,All,10^9 tonne-km / yr,Shipping,Coastal,Freight Activity
2,Freight,International Transport Forum,Canada,1997,10.735,All,All,10^9 tonne-km / yr,Shipping,Coastal,Freight Activity
3,Freight,International Transport Forum,Canada,1998,13.420,All,All,10^9 tonne-km / yr,Shipping,Coastal,Freight Activity
4,Freight,International Transport Forum,Canada,1999,14.144,All,All,10^9 tonne-km / yr,Shipping,Coastal,Freight Activity
...,...,...,...,...,...,...,...,...,...,...,...
1428,Freight,International Transport Forum,Turkey,2014,18.553,All,All,10^9 tonne-km / yr,Shipping,Coastal,Freight Activity
1429,Freight,International Transport Forum,Turkey,2015,19.189,All,All,10^9 tonne-km / yr,Shipping,Coastal,Freight Activity
1430,Freight,International Transport Forum,Turkey,2016,19.492,All,All,10^9 tonne-km / yr,Shipping,Coastal,Freight Activity
1431,Freight,International Transport Forum,Turkey,2017,22.087,All,All,10^9 tonne-km / yr,Shipping,Coastal,Freight Activity
1432,Freight,International Transport Forum,Turkey,2018,21.779,All,All,10^9 tonne-km / yr,Shipping,Coastal,Freight Activity

# Reordering the columns
    Rule: The columns should follow the order established in the latest template

In [16]:
columnsTitles = ['Source', 'Region', 'Variable','Unit','Service','Mode','Vehicle Type','Technology','Fuel','Value','Year']
df = df.reindex(columns=columnsTitles)
df

,Source,Region,Variable,Unit,Service,Mode,Vehicle Type,Technology,Fuel,Value,Year
0,International Transport Forum,Canada,Freight Activity,10^9 tonne-km / yr,Freight,Shipping,Coastal,All,All,10.369,1995
1,International Transport Forum,Canada,Freight Activity,10^9 tonne-km / yr,Freight,Shipping,Coastal,All,All,10.166,1996
2,International Transport Forum,Canada,Freight Activity,10^9 tonne-km / yr,Freight,Shipping,Coastal,All,All,10.735,1997
3,International Transport Forum,Canada,Freight Activity,10^9 tonne-km / yr,Freight,Shipping,Coastal,All,All,13.420,1998
4,International Transport Forum,Canada,Freight Activity,10^9 tonne-km / yr,Freight,Shipping,Coastal,All,All,14.144,1999
...,...,...,...,...,...,...,...,...,...,...,...
1428,International Transport Forum,Turkey,Freight Activity,10^9 tonne-km / yr,Freight,Shipping,Coastal,All,All,18.553,2014
1429,International Transport Forum,Turkey,Freight Activity,10^9 tonne-km / yr,Freight,Shipping,Coastal,All,All,19.189,2015
1430,International Transport Forum,Turkey,Freight Activity,10^9 tonne-km / yr,Freight,Shipping,Coastal,All,All,19.492,2016
1431,International Transport Forum,Turkey,Freight Activity,10^9 tonne-km / yr,Freight,Shipping,Coastal,All,All,22.087,2017
1432,International Transport Forum,Turkey,Freight Activity,10^9 tonne-km / yr,Freight,Shipping,Coastal,All,All,21.779,2018

# Exporting Result - Programming Friendly View

In [18]:
# Setting the column id for the dataframe
df["ID"] = [data_id] *len(df)

# Exporting results
df.to_csv(raw_data_csv_path+data_id+"_cleaned_PF.csv",index=False)

# Exporting Result - User Friendly View

In [19]:
# Get the columns to preserve
columns_to_preserve = ['Source','Region','Variable','Unit','Service','Mode','Vehicle Type','Technology','Fuel']

# Grouping by country
group_by_country = df.groupby(df.Region)

# Getting the list of countries
list_of_countries = list(group_by_country.groups.keys())

# Saving the dict of all the final dataframes of each country
dict_of_final_dataframes_per_country = {}

# For each country, perform the following algorithm
for country in list_of_countries:
    
    # Get the df corresponding to the given country
    df_country_X = group_by_country.get_group(country)
    
    # Get the list of years available for the given year
    list_of_years_for_country_X = list(set(df_country_X["Year"]))

    # Group the data of country X by year
    group_by_year_country_X = df_country_X.groupby(df_country_X.Year)
    
    # Create a structure that will hold the dataframes of each year
    df_per_year_for_country_X = {}
    
    # Obtain the dataframe for each year
    for name, group in group_by_year_country_X:
        df_per_year_for_country_X[name] = group

    # Do the necessary processing required in the DF of each year
    for year in list_of_years_for_country_X:
        
        # Obtain the dataframe for country X in year Y
        df_country_X_in_year_Y = df_per_year_for_country_X[year]
        
        # Renaming and droping columns
        df_country_X_in_year_Y.rename(columns={"Value":year}, inplace = True)
        df_country_X_in_year_Y.drop(columns=["Year"], inplace = True)

    # Concatenating all the dataframes of a given country into a single dataframe
    list_of_all_df_for_country_X = list(df_per_year_for_country_X.values())
    df_concat_all_dfs_for_country_x = pd.concat(list_of_all_df_for_country_X,sort=False, verify_integrity=True,join='outer')

    # Creating the final df for country X by eliminating all NAN and combining rows
    final_df_for_country_x = df_concat_all_dfs_for_country_x.groupby(columns_to_preserve)[list_of_years_for_country_X].first().reset_index()

    # Saving the final df of country X in the list of all countries df
    dict_of_final_dataframes_per_country[country] = final_df_for_country_x

# Concatenate all the dataframes of the countries
list_df_for_all_countries_final = list(dict_of_final_dataframes_per_country.values())
df_with_all_countries_data = pd.concat(list_df_for_all_countries_final,sort=False, verify_integrity=True,join='outer',ignore_index=True)

# Setting the column id for the dataframe
df_with_all_countries_data["ID"] = [data_id] *len(df_with_all_countries_data)

# Exporting the final dataframe
df_with_all_countries_data.to_csv(raw_data_csv_path+data_id+"_cleaned_UF.csv",index=False)